export interface ToolMetadata {
  slug: string;
  name: string;
  tagline: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string;
  category: 'fundraising' | 'legal' | 'security' | 'calculators';
  icon: string; // Lucide icon name
  popular?: boolean;
  estimatedTime: string;
  features: string[];
  ctaText: string;
  ctaRoute: string;
  faqs: { question: string; answer: string }[];
}

export const toolsList: ToolMetadata[] = [
  {
    slug: 'pitch-deck-analyzer',
    name: 'Free Pitch Deck Analyzer & Grader',
    tagline: 'Instant slide count, section analysis, and investor engagement score for your pitch deck.',
    metaTitle: 'Free Pitch Deck Analyzer & Grader (2026) — Check Your Deck | DocTransfer',
    metaDescription: 'Upload your pitch deck PDF for an instant 0–100 score on slide count, section completeness (Team, Financials, Traction), and investor reading time optimization.',
    keywords: 'pitch deck analyzer, pitch deck grader free, check pitch deck length, pitch deck feedback tool, pitch deck score, investor pitch deck check',
    category: 'fundraising',
    icon: 'FileSpreadsheet',
    popular: true,
    estimatedTime: '< 1 min',
    features: [
      'Automatic slide count evaluation against 10–14 slide benchmarks',
      'AI section detection (Team, Financials, Market, Traction, Solution)',
      'File size and mobile optimization audit',
      'Investor reading time prediction and actionable recommendations'
    ],
    ctaText: 'Analyze My Pitch Deck Free',
    ctaRoute: '/tools/pitch-deck-analyzer',
    faqs: [
      {
        question: 'How does the Pitch Deck Analyzer grade my deck?',
        answer: 'Our tool extracts text and metadata from your PDF client-side to evaluate slide count against our 12,847 pitch deck benchmark database. It checks for critical sections (Team, Financials, Market Size, Traction) and calculates an investor readiness score from 0 to 100.'
      },
      {
        question: 'Is my pitch deck kept confidential during analysis?',
        answer: 'Yes, 100%. All PDF processing happens locally in your browser using web standards. Your pitch deck is never uploaded to external server storage unless you explicitly choose to create a secure DocTransfer share link.'
      },
      {
        question: 'What is the ideal pitch deck slide length?',
        answer: 'According to our 2026 Pitch Deck Benchmarks report, the optimal length for funded pitch decks is 10 to 14 slides. Decks exceeding 20 slides experience a 34% drop-off rate among VC viewers.'
      }
    ]
  },
  {
    slug: 'nda-generator',
    name: 'Free Interactive NDA Generator',
    tagline: 'Create, customize, and download legally binding Mutual or Unilateral NDAs in 2 minutes.',
    metaTitle: 'Free NDA Generator — Create Non-Disclosure Agreement Online | DocTransfer',
    metaDescription: 'Generate customized Mutual (2-way) or Unilateral (1-way) Non-Disclosure Agreements for free. Download PDF instantly or send for digital e-signature.',
    keywords: 'free NDA generator, online NDA creator, create non-disclosure agreement free, mutual NDA builder, unilateral NDA maker, legal agreement generator',
    category: 'legal',
    icon: 'FileCheck',
    popular: true,
    estimatedTime: '2 mins',
    features: [
      'Build Mutual (2-way) or Unilateral (1-way) NDAs instantly',
      'Custom confidentiality period (1, 2, 3, or 5 years)',
      'US State & International jurisdiction selection',
      'Download clean PDF or send for instant e-signature'
    ],
    ctaText: 'Build Free NDA Now',
    ctaRoute: '/tools/nda-generator',
    faqs: [
      {
        question: 'Are the NDAs generated by DocTransfer legally binding?',
        answer: 'Yes. The generated NDAs incorporate standard commercial non-disclosure terms recognized across US state courts and international jurisdictions. When signed via DocTransfer e-signature, they comply with the ESIGN Act and eIDAS.'
      },
      {
        question: 'What is the difference between a Mutual and Unilateral NDA?',
        answer: 'A Unilateral NDA protects one disclosing party (e.g. hiring a freelancer), while a Mutual NDA protects both parties when sharing reciprocal trade secrets (e.g. strategic partnership or M&A due diligence).'
      }
    ]
  },
  {
    slug: 'vdr-cost-calculator',
    name: 'Virtual Data Room (VDR) ROI Calculator',
    tagline: 'Compare DocSend and enterprise VDR costs against DocTransfer and calculate your annual savings.',
    metaTitle: 'Virtual Data Room Cost & ROI Calculator — Compare VDR Pricing | DocTransfer',
    metaDescription: 'Calculate how much you can save by switching from DocSend, Firmex, or Datasite to DocTransfer. Interactive ROI slider for team seats and data rooms.',
    keywords: 'virtual data room pricing calculator, DocSend cost comparison, VDR ROI calculator, data room price comparison, cheap virtual data room',
    category: 'calculators',
    icon: 'Calculator',
    popular: false,
    estimatedTime: '30 secs',
    features: [
      'Interactive team seats & document volume sliders',
      'Direct pricing comparison against DocSend, Firmex, and Datasite',
      'Instant dollar & percentage annual savings breakdown',
      'Export ROI breakdown chart'
    ],
    ctaText: 'Calculate Savings',
    ctaRoute: '/tools/vdr-cost-calculator',
    faqs: [
      {
        question: 'How much does DocSend cost compared to DocTransfer?',
        answer: 'DocSend charges $45/user/month (Standard) to $150/user/month (Advanced) with strict seat limits. DocTransfer offers a 100% Free core plan and a $39/mo Business tier with unlimited document tracking.'
      },
      {
        question: 'Why are traditional VDRs so expensive?',
        answer: 'Legacy VDR providers (Datasite, Intralinks) charge per-page upload fees ($0.60–$1.00/page) and enterprise seat licensing, resulting in $1,000–$5,000+ monthly bills for simple M&A due diligence.'
      }
    ]
  },
  {
    slug: 'pdf-watermarking-tool',
    name: 'Free PDF Watermark Tool & Security Audit',
    tagline: 'Apply dynamic confidential text, recipient email, and date watermarks to your PDF files client-side.',
    metaTitle: 'Free PDF Watermark Tool — Add Confidential Watermarks Online | DocTransfer',
    metaDescription: 'Add custom dynamic text watermarks (Confidential, Recipient Email, Date) to your PDF files free online. 100% private browser-side processing.',
    keywords: 'add watermark to PDF free online, PDF security tool, confidential watermark generator, protect pitch deck watermark, pdf watermark maker',
    category: 'security',
    icon: 'ShieldCheck',
    popular: false,
    estimatedTime: '1 min',
    features: [
      'Custom watermark text, email, and timestamp overlays',
      'Adjustable opacity, rotation angle, font size, and color',
      '100% local client-side processing (PDF never leaves browser)',
      'Download watermarked PDF instantly'
    ],
    ctaText: 'Watermark PDF Free',
    ctaRoute: '/tools/pdf-watermarking-tool',
    faqs: [
      {
        question: 'Does this watermark tool upload my PDF to a server?',
        answer: 'No. The watermarking algorithm runs entirely inside your browser using client-side JavaScript (pdf-lib). Your document content stays 100% private.'
      },
      {
        question: 'Why should I watermark sensitive documents?',
        answer: 'Watermarking prevents unauthorized screenshot sharing and identifies leaks by linking shared copies to specific recipient names or timestamps.'
      }
    ]
  }
];

export function getToolBySlug(slug: string): ToolMetadata | undefined {
  return toolsList.find(t => t.slug === slug);
}
